//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 11:02:21 AM CET 
//


package org.purl.dc.terms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.purl.dc.terms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Identifier_QNAME = new QName("http://purl.org/dc/terms/", "identifier");
    private final static QName _Title_QNAME = new QName("http://purl.org/dc/terms/", "title");
    private final static QName _Type_QNAME = new QName("http://purl.org/dc/terms/", "type");
    private final static QName _Modified_QNAME = new QName("http://purl.org/dc/terms/", "modified");
    private final static QName _Creator_QNAME = new QName("http://purl.org/dc/terms/", "creator");
    private final static QName _Spatial_QNAME = new QName("http://purl.org/dc/terms/", "spatial");
    private final static QName _Temporal_QNAME = new QName("http://purl.org/dc/terms/", "temporal");
    private final static QName _Language_QNAME = new QName("http://purl.org/dc/terms/", "language");
    private final static QName _Abstract_QNAME = new QName("http://purl.org/dc/terms/", "abstract");
    private final static QName _AccessRights_QNAME = new QName("http://purl.org/dc/terms/", "accessRights");
    private final static QName _Alternative_QNAME = new QName("http://purl.org/dc/terms/", "alternative");
    private final static QName _Audience_QNAME = new QName("http://purl.org/dc/terms/", "audience");
    private final static QName _Available_QNAME = new QName("http://purl.org/dc/terms/", "available");
    private final static QName _ConformsTo_QNAME = new QName("http://purl.org/dc/terms/", "conformsTo");
    private final static QName _Contributor_QNAME = new QName("http://purl.org/dc/terms/", "contributor");
    private final static QName _Coverage_QNAME = new QName("http://purl.org/dc/terms/", "coverage");
    private final static QName _Created_QNAME = new QName("http://purl.org/dc/terms/", "created");
    private final static QName _Date_QNAME = new QName("http://purl.org/dc/terms/", "date");
    private final static QName _DateAccepted_QNAME = new QName("http://purl.org/dc/terms/", "dateAccepted");
    private final static QName _DateCopyrighted_QNAME = new QName("http://purl.org/dc/terms/", "dateCopyrighted");
    private final static QName _DateSubmitted_QNAME = new QName("http://purl.org/dc/terms/", "dateSubmitted");
    private final static QName _Description_QNAME = new QName("http://purl.org/dc/terms/", "description");
    private final static QName _EducationLevel_QNAME = new QName("http://purl.org/dc/terms/", "educationLevel");
    private final static QName _Extent_QNAME = new QName("http://purl.org/dc/terms/", "extent");
    private final static QName _Format_QNAME = new QName("http://purl.org/dc/terms/", "format");
    private final static QName _HasFormat_QNAME = new QName("http://purl.org/dc/terms/", "hasFormat");
    private final static QName _HasPart_QNAME = new QName("http://purl.org/dc/terms/", "hasPart");
    private final static QName _HasVersion_QNAME = new QName("http://purl.org/dc/terms/", "hasVersion");
    private final static QName _InstructionalMethod_QNAME = new QName("http://purl.org/dc/terms/", "instructionalMethod");
    private final static QName _IsFormatOf_QNAME = new QName("http://purl.org/dc/terms/", "isFormatOf");
    private final static QName _IsPartOf_QNAME = new QName("http://purl.org/dc/terms/", "isPartOf");
    private final static QName _IsReferencedBy_QNAME = new QName("http://purl.org/dc/terms/", "isReferencedBy");
    private final static QName _IsReplacedBy_QNAME = new QName("http://purl.org/dc/terms/", "isReplacedBy");
    private final static QName _IsRequiredBy_QNAME = new QName("http://purl.org/dc/terms/", "isRequiredBy");
    private final static QName _IsVersionOf_QNAME = new QName("http://purl.org/dc/terms/", "isVersionOf");
    private final static QName _Issued_QNAME = new QName("http://purl.org/dc/terms/", "issued");
    private final static QName _License_QNAME = new QName("http://purl.org/dc/terms/", "license");
    private final static QName _Mediator_QNAME = new QName("http://purl.org/dc/terms/", "mediator");
    private final static QName _Provenance_QNAME = new QName("http://purl.org/dc/terms/", "provenance");
    private final static QName _Publisher_QNAME = new QName("http://purl.org/dc/terms/", "publisher");
    private final static QName _References_QNAME = new QName("http://purl.org/dc/terms/", "references");
    private final static QName _Relation_QNAME = new QName("http://purl.org/dc/terms/", "relation");
    private final static QName _Replaces_QNAME = new QName("http://purl.org/dc/terms/", "replaces");
    private final static QName _Requires_QNAME = new QName("http://purl.org/dc/terms/", "requires");
    private final static QName _Rights_QNAME = new QName("http://purl.org/dc/terms/", "rights");
    private final static QName _RightsHolder_QNAME = new QName("http://purl.org/dc/terms/", "rightsHolder");
    private final static QName _Source_QNAME = new QName("http://purl.org/dc/terms/", "source");
    private final static QName _Subject_QNAME = new QName("http://purl.org/dc/terms/", "subject");
    private final static QName _TableOfContents_QNAME = new QName("http://purl.org/dc/terms/", "tableOfContents");
    private final static QName _Valid_QNAME = new QName("http://purl.org/dc/terms/", "valid");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.purl.dc.terms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FreeText }
     * 
     */
    public FreeText createFreeText() {
        return new FreeText();
    }

    /**
     * Create an instance of {@link InformationType }
     * 
     */
    public InformationType createInformationType() {
        return new InformationType();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PeriodOfTime }
     * 
     */
    public PeriodOfTime createPeriodOfTime() {
        return new PeriodOfTime();
    }

    /**
     * Create an instance of {@link TripleType }
     * 
     */
    public TripleType createTripleType() {
        return new TripleType();
    }

    /**
     * Create an instance of {@link AgentClassOrFreeText }
     * 
     */
    public AgentClassOrFreeText createAgentClassOrFreeText() {
        return new AgentClassOrFreeText();
    }

    /**
     * Create an instance of {@link InformationObject }
     * 
     */
    public InformationObject createInformationObject() {
        return new InformationObject();
    }

    /**
     * Create an instance of {@link AgentOrFreeText }
     * 
     */
    public AgentOrFreeText createAgentOrFreeText() {
        return new AgentOrFreeText();
    }

    /**
     * Create an instance of {@link BeslissendOrgaan }
     * 
     */
    public BeslissendOrgaan createBeslissendOrgaan() {
        return new BeslissendOrgaan();
    }

    /**
     * Create an instance of {@link OriginalLocation }
     * 
     */
    public OriginalLocation createOriginalLocation() {
        return new OriginalLocation();
    }

    /**
     * Create an instance of {@link OriginalAgent }
     * 
     */
    public OriginalAgent createOriginalAgent() {
        return new OriginalAgent();
    }

    /**
     * Create an instance of {@link OriginalInformationType }
     * 
     */
    public OriginalInformationType createOriginalInformationType() {
        return new OriginalInformationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "identifier")
    public JAXBElement<String> createIdentifier(String value) {
        return new JAXBElement<String>(_Identifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "title")
    public JAXBElement<FreeText> createTitle(FreeText value) {
        return new JAXBElement<FreeText>(_Title_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "type")
    public JAXBElement<InformationType> createType(InformationType value) {
        return new JAXBElement<InformationType>(_Type_QNAME, InformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "modified")
    public JAXBElement<String> createModified(String value) {
        return new JAXBElement<String>(_Modified_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Agent }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Agent }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "creator")
    public JAXBElement<Agent> createCreator(Agent value) {
        return new JAXBElement<Agent>(_Creator_QNAME, Agent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Location }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "spatial")
    public JAXBElement<Location> createSpatial(Location value) {
        return new JAXBElement<Location>(_Spatial_QNAME, Location.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "temporal")
    public JAXBElement<PeriodOfTime> createTemporal(PeriodOfTime value) {
        return new JAXBElement<PeriodOfTime>(_Temporal_QNAME, PeriodOfTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "abstract")
    public JAXBElement<FreeText> createAbstract(FreeText value) {
        return new JAXBElement<FreeText>(_Abstract_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "accessRights")
    public JAXBElement<TripleType> createAccessRights(TripleType value) {
        return new JAXBElement<TripleType>(_AccessRights_QNAME, TripleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "alternative")
    public JAXBElement<FreeText> createAlternative(FreeText value) {
        return new JAXBElement<FreeText>(_Alternative_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentClassOrFreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AgentClassOrFreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "audience")
    public JAXBElement<AgentClassOrFreeText> createAudience(AgentClassOrFreeText value) {
        return new JAXBElement<AgentClassOrFreeText>(_Audience_QNAME, AgentClassOrFreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "available")
    public JAXBElement<PeriodOfTime> createAvailable(PeriodOfTime value) {
        return new JAXBElement<PeriodOfTime>(_Available_QNAME, PeriodOfTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "conformsTo")
    public JAXBElement<InformationObject> createConformsTo(InformationObject value) {
        return new JAXBElement<InformationObject>(_ConformsTo_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentOrFreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AgentOrFreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "contributor")
    public JAXBElement<AgentOrFreeText> createContributor(AgentOrFreeText value) {
        return new JAXBElement<AgentOrFreeText>(_Contributor_QNAME, AgentOrFreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "coverage")
    public JAXBElement<FreeText> createCoverage(FreeText value) {
        return new JAXBElement<FreeText>(_Coverage_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "created")
    public JAXBElement<String> createCreated(String value) {
        return new JAXBElement<String>(_Created_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "dateAccepted")
    public JAXBElement<String> createDateAccepted(String value) {
        return new JAXBElement<String>(_DateAccepted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "dateCopyrighted")
    public JAXBElement<String> createDateCopyrighted(String value) {
        return new JAXBElement<String>(_DateCopyrighted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "dateSubmitted")
    public JAXBElement<String> createDateSubmitted(String value) {
        return new JAXBElement<String>(_DateSubmitted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "description")
    public JAXBElement<FreeText> createDescription(FreeText value) {
        return new JAXBElement<FreeText>(_Description_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentClassOrFreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AgentClassOrFreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "educationLevel")
    public JAXBElement<AgentClassOrFreeText> createEducationLevel(AgentClassOrFreeText value) {
        return new JAXBElement<AgentClassOrFreeText>(_EducationLevel_QNAME, AgentClassOrFreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "extent")
    public JAXBElement<FreeText> createExtent(FreeText value) {
        return new JAXBElement<FreeText>(_Extent_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "format")
    public JAXBElement<FreeText> createFormat(FreeText value) {
        return new JAXBElement<FreeText>(_Format_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "hasFormat")
    public JAXBElement<InformationObject> createHasFormat(InformationObject value) {
        return new JAXBElement<InformationObject>(_HasFormat_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "hasPart")
    public JAXBElement<InformationObject> createHasPart(InformationObject value) {
        return new JAXBElement<InformationObject>(_HasPart_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "hasVersion")
    public JAXBElement<InformationObject> createHasVersion(InformationObject value) {
        return new JAXBElement<InformationObject>(_HasVersion_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "instructionalMethod")
    public JAXBElement<FreeText> createInstructionalMethod(FreeText value) {
        return new JAXBElement<FreeText>(_InstructionalMethod_QNAME, FreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isFormatOf")
    public JAXBElement<InformationObject> createIsFormatOf(InformationObject value) {
        return new JAXBElement<InformationObject>(_IsFormatOf_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isPartOf")
    public JAXBElement<InformationObject> createIsPartOf(InformationObject value) {
        return new JAXBElement<InformationObject>(_IsPartOf_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isReferencedBy")
    public JAXBElement<InformationObject> createIsReferencedBy(InformationObject value) {
        return new JAXBElement<InformationObject>(_IsReferencedBy_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isReplacedBy")
    public JAXBElement<InformationObject> createIsReplacedBy(InformationObject value) {
        return new JAXBElement<InformationObject>(_IsReplacedBy_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isRequiredBy")
    public JAXBElement<InformationObject> createIsRequiredBy(InformationObject value) {
        return new JAXBElement<InformationObject>(_IsRequiredBy_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isVersionOf")
    public JAXBElement<InformationObject> createIsVersionOf(InformationObject value) {
        return new JAXBElement<InformationObject>(_IsVersionOf_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "issued")
    public JAXBElement<String> createIssued(String value) {
        return new JAXBElement<String>(_Issued_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "license")
    public JAXBElement<TripleType> createLicense(TripleType value) {
        return new JAXBElement<TripleType>(_License_QNAME, TripleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentClassOrFreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AgentClassOrFreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "mediator")
    public JAXBElement<AgentClassOrFreeText> createMediator(AgentClassOrFreeText value) {
        return new JAXBElement<AgentClassOrFreeText>(_Mediator_QNAME, AgentClassOrFreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "provenance")
    public JAXBElement<TripleType> createProvenance(TripleType value) {
        return new JAXBElement<TripleType>(_Provenance_QNAME, TripleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentOrFreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AgentOrFreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "publisher")
    public JAXBElement<AgentOrFreeText> createPublisher(AgentOrFreeText value) {
        return new JAXBElement<AgentOrFreeText>(_Publisher_QNAME, AgentOrFreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "references")
    public JAXBElement<InformationObject> createReferences(InformationObject value) {
        return new JAXBElement<InformationObject>(_References_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "relation")
    public JAXBElement<InformationObject> createRelation(InformationObject value) {
        return new JAXBElement<InformationObject>(_Relation_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "replaces")
    public JAXBElement<InformationObject> createReplaces(InformationObject value) {
        return new JAXBElement<InformationObject>(_Replaces_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "requires")
    public JAXBElement<InformationObject> createRequires(InformationObject value) {
        return new JAXBElement<InformationObject>(_Requires_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "rights")
    public JAXBElement<TripleType> createRights(TripleType value) {
        return new JAXBElement<TripleType>(_Rights_QNAME, TripleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentOrFreeText }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AgentOrFreeText }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "rightsHolder")
    public JAXBElement<AgentOrFreeText> createRightsHolder(AgentOrFreeText value) {
        return new JAXBElement<AgentOrFreeText>(_RightsHolder_QNAME, AgentOrFreeText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "source")
    public JAXBElement<InformationObject> createSource(InformationObject value) {
        return new JAXBElement<InformationObject>(_Source_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "subject")
    public JAXBElement<TripleType> createSubject(TripleType value) {
        return new JAXBElement<TripleType>(_Subject_QNAME, TripleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "tableOfContents")
    public JAXBElement<InformationObject> createTableOfContents(InformationObject value) {
        return new JAXBElement<InformationObject>(_TableOfContents_QNAME, InformationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "valid")
    public JAXBElement<PeriodOfTime> createValid(PeriodOfTime value) {
        return new JAXBElement<PeriodOfTime>(_Valid_QNAME, PeriodOfTime.class, null, value);
    }

}
