swagger: "2.0"
info:
 description: "Samenwerkende Catalogi CPSV-AP API"
 version: "1.0.0"
 title: "Samenwerkende Catalogi CPSV-AP API"
 termsOfService: "EUPL"
 contact:
   email: "Marco.Aarts@ictu.nl"
 license:
   name: "EUPL"
   url: "https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12"
host: "localhost:8080"
basePath: "/api"
tags:
- name: "api"
  description: "Samenwerkende Catalogi CPSV-AP API"
  externalDocs:
   description: "Find out more"
   url: "https://www.logius.nl/diensten/samenwerkende-catalogi/documentatie"
schemes:
- "http"
paths:
 /PublicServices:
   get:
     tags:
     - "api"
     summary: "Get list of Public services"
     description: "Get a list of Public services"
     operationId: "GetPublicServices"
     produces:
     - "application/json"
     - "application/xml"
     - "application/ld+json"
     - "application/x-jackson-smile"
     - "avro/binary"    
     - "application/cbor"
     - "application/protobuf"
     - "application/ion"
     - "application/msgpack"
     - "application/bson"
     parameters:
     - name: "startRecord"
       in: "query"
       description: "start Record"
       required: true
       type: "string"
       default: "1"
     - name: "maximumRecords"
       in: "query"
       description: "maximum Record"
       required: true
       type: "string"
       default: "10"
     - name: "query"
       in: "query"
       description: "query"
       required: true
       type: "string"
     responses:
       200:
         description: "successful operation"
         schema:
           $ref: "#/definitions/PublicServiceDataset" 
       400:
         description: "Invalid status value"
 
definitions:

 
 PublicServiceDataset:
   type: "object"
   properties:
     hasPart:
       type: "array"
       items:
         $ref: "#/definitions/PublicService"
       xml:
         wrapped: true
   xml:
         name: "PublicServiceDataset"

 PublicService:
   type: "object"
   properties:
     id: 
       type: "string"
       xml:
         name: "id"
     title: 
       type: "string"
       xml:
         name: "title"
     description: 
       type: "string"
       xml:
         name: "id"
     type: 
       $ref: "#/definitions/Concept"
     language: 
       $ref: "#/definitions/Language"
     spatial: 
       $ref: "#/definitions/Location"
     hasCompetentAuthority:
       $ref: "#/definitions/PublicOrganisation"
   xml:
     name: "PublicService"

 PublicOrganisation:
   type: "object"
   properties:
     id: 
       type: "string"
       xml:
         name: "id"
     spatial: 
       $ref: "#/definitions/Location"
   xml:
     name: "PublicService"

 Location:
   type: "object"
   properties:
     id: 
       type: "string"
       xml:
         name: "id"
   xml:
     name: "Location"

 Concept:
   type: "object"
   properties:
     id: 
       type: "string"
       xml:
         name: "id"
   xml:
     name: "Concept"

 Language:
   type: "object"
   properties:
     id: 
       type: "string"
       xml:
         name: "id"
   xml:
     name: "Language"

externalDocs:
 description: "Find out more about Swagger"
 url: "http://swagger.io"