prefix sh: <http://www.w3.org/ns/shacl#>
prefix dct: <http://purl.org/dc/terms/>
SELECT  (count(?violation) as ?violations) ?name
WHERE {
?vr a sh:ValidationResult . 
?vr sh:resultMessage ?resultMessage .
?vr sh:resultPath ?resultPath .
?vr sh:resultSeverity ?resultSeverity .	
?vr sh:sourceConstraintComponent ?sourceConstraintComponent .
?vr sh:sourceShape ?sourceShape .
?report dct:profile ?profile .
?report sh:result ?vr.
FILTER (?profile="DCAT-AP-ASIP") .
FILTER (!isBlank(?sourceShape)) .
BIND(strafter(str(?sourceShape), "http://esante.gouv.fr/profile/ns#" ) as ?name) .
BIND(concat(str(?resultMessage), str(?resultPath), str(?resultSeverity), str(?sourceConstraintComponent), str(?sourceShape)) as ?violation) .
}
GROUP BY (?name)
ORDER BY DESC(?violations)
LIMIT 6