//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 09:39:11 PM CET 
//


package test;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gzdDataComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gzdDataComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="originalData" type="{http://standaarden.overheid.nl/sru}freeElementsComplexType"/&gt;
 *         &lt;element name="enrichedData" type="{http://standaarden.overheid.nl/sru}freeElementsComplexType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="gzd", namespace="http://standaarden.overheid.nl/sru")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gzdDataComplexType", propOrder = {
    "originalData",
    "enrichedData"
})
public class GzdDataComplexType {

    @XmlElement(required = true)
    protected FreeElementsComplexType originalData;
    protected FreeElementsComplexType enrichedData;

    /**
     * Gets the value of the originalData property.
     * 
     * @return
     *     possible object is
     *     {@link FreeElementsComplexType }
     *     
     */
    public FreeElementsComplexType getOriginalData() {
        return originalData;
    }

    /**
     * Sets the value of the originalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeElementsComplexType }
     *     
     */
    public void setOriginalData(FreeElementsComplexType value) {
        this.originalData = value;
    }

    /**
     * Gets the value of the enrichedData property.
     * 
     * @return
     *     possible object is
     *     {@link FreeElementsComplexType }
     *     
     */
    public FreeElementsComplexType getEnrichedData() {
        return enrichedData;
    }

    /**
     * Sets the value of the enrichedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeElementsComplexType }
     *     
     */
    public void setEnrichedData(FreeElementsComplexType value) {
        this.enrichedData = value;
    }

}
