//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 11:02:21 AM CET 
//


package nl.overheid.standaarden.product.terms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.purl.dc.terms.AgentClassOrFreeText;
import org.purl.dc.terms.FreeText;
import org.purl.dc.terms.InformationType;
import org.purl.dc.terms.Location;
import org.purl.dc.terms.PeriodOfTime;
import org.purl.dc.terms.TripleType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="owmskern"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;group ref="{http://standaarden.overheid.nl/owms/terms/}owmskern"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="owmsmantel" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://purl.org/dc/terms/}audience" maxOccurs="2"/&gt;
 *                   &lt;element ref="{http://purl.org/dc/terms/}subject" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element ref="{http://purl.org/dc/terms/}abstract"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="scmeta" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="productID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="onlineAanvragen"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="ja"/&gt;
 *                         &lt;enumeration value="digid"/&gt;
 *                         &lt;enumeration value="nee"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="aanvraagURL" type="{http://standaarden.overheid.nl/product/terms/}InformationObject" minOccurs="0"/&gt;
 *                   &lt;element name="eenmaligAanmelden" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="ja"/&gt;
 *                         &lt;enumeration value="nee"/&gt;
 *                         &lt;enumeration value="digi-d"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="contactpunt" type="{http://standaarden.overheid.nl/product/terms/}InformationObject" minOccurs="0"/&gt;
 *                   &lt;element name="uniformeProductnaam" type="{http://standaarden.overheid.nl/product/terms/}UniformeProductnaam" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="gerelateerdProduct" type="{http://standaarden.overheid.nl/product/terms/}UniformeProductnaam" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "owmskern",
    "owmsmantel",
    "scmeta"
})
@XmlRootElement(name = "meta")
public class Meta {

    @XmlElement(required = true)
    protected Meta.Owmskern owmskern;
    protected Meta.Owmsmantel owmsmantel;
    protected Meta.Scmeta scmeta;

    /**
     * Gets the value of the owmskern property.
     * 
     * @return
     *     possible object is
     *     {@link Meta.Owmskern }
     *     
     */
    public Meta.Owmskern getOwmskern() {
        return owmskern;
    }

    /**
     * Sets the value of the owmskern property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta.Owmskern }
     *     
     */
    public void setOwmskern(Meta.Owmskern value) {
        this.owmskern = value;
    }

    /**
     * Gets the value of the owmsmantel property.
     * 
     * @return
     *     possible object is
     *     {@link Meta.Owmsmantel }
     *     
     */
    public Meta.Owmsmantel getOwmsmantel() {
        return owmsmantel;
    }

    /**
     * Sets the value of the owmsmantel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta.Owmsmantel }
     *     
     */
    public void setOwmsmantel(Meta.Owmsmantel value) {
        this.owmsmantel = value;
    }

    /**
     * Gets the value of the scmeta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta.Scmeta }
     *     
     */
    public Meta.Scmeta getScmeta() {
        return scmeta;
    }

    /**
     * Sets the value of the scmeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta.Scmeta }
     *     
     */
    public void setScmeta(Meta.Scmeta value) {
        this.scmeta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;group ref="{http://standaarden.overheid.nl/owms/terms/}owmskern"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifier",
        "title",
        "language",
        "type",
        "creator",
        "modified",
        "spatial",
        "temporal",
        "authority"
    })
    public static class Owmskern {

        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String identifier;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        protected FreeText title;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "language")
        protected List<String> language;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        protected InformationType type;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected List<org.purl.dc.terms.Agent> creator;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        protected String modified;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected List<Location> spatial;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected PeriodOfTime temporal;
        @XmlElement(namespace = "http://standaarden.overheid.nl/owms/terms/")
        protected List<nl.overheid.standaarden.owms.terms.Agent> authority;

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifier(String value) {
            this.identifier = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link FreeText }
         *     
         */
        public FreeText getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link FreeText }
         *     
         */
        public void setTitle(FreeText value) {
            this.title = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLanguage() {
            if (language == null) {
                language = new ArrayList<String>();
            }
            return this.language;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link InformationType }
         *     
         */
        public InformationType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link InformationType }
         *     
         */
        public void setType(InformationType value) {
            this.type = value;
        }

        /**
         * Gets the value of the creator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the creator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCreator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link org.purl.dc.terms.Agent }
         * 
         * 
         */
        public List<org.purl.dc.terms.Agent> getCreator() {
            if (creator == null) {
                creator = new ArrayList<org.purl.dc.terms.Agent>();
            }
            return this.creator;
        }

        /**
         * Gets the value of the modified property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModified() {
            return modified;
        }

        /**
         * Sets the value of the modified property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModified(String value) {
            this.modified = value;
        }

        /**
         * Gets the value of the spatial property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the spatial property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSpatial().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Location }
         * 
         * 
         */
        public List<Location> getSpatial() {
            if (spatial == null) {
                spatial = new ArrayList<Location>();
            }
            return this.spatial;
        }

        /**
         * Gets the value of the temporal property.
         * 
         * @return
         *     possible object is
         *     {@link PeriodOfTime }
         *     
         */
        public PeriodOfTime getTemporal() {
            return temporal;
        }

        /**
         * Sets the value of the temporal property.
         * 
         * @param value
         *     allowed object is
         *     {@link PeriodOfTime }
         *     
         */
        public void setTemporal(PeriodOfTime value) {
            this.temporal = value;
        }

        /**
         * Gets the value of the authority property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the authority property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuthority().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link nl.overheid.standaarden.owms.terms.Agent }
         * 
         * 
         */
        public List<nl.overheid.standaarden.owms.terms.Agent> getAuthority() {
            if (authority == null) {
                authority = new ArrayList<nl.overheid.standaarden.owms.terms.Agent>();
            }
            return this.authority;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://purl.org/dc/terms/}audience" maxOccurs="2"/&gt;
     *         &lt;element ref="{http://purl.org/dc/terms/}subject" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element ref="{http://purl.org/dc/terms/}abstract"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "audience",
        "subject",
        "_abstract"
    })
    public static class Owmsmantel {

        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        protected List<AgentClassOrFreeText> audience;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected List<TripleType> subject;
        @XmlElement(name = "abstract", namespace = "http://purl.org/dc/terms/", required = true)
        protected FreeText _abstract;

        /**
         * Gets the value of the audience property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the audience property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAudience().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AgentClassOrFreeText }
         * 
         * 
         */
        public List<AgentClassOrFreeText> getAudience() {
            if (audience == null) {
                audience = new ArrayList<AgentClassOrFreeText>();
            }
            return this.audience;
        }

        /**
         * Gets the value of the subject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TripleType }
         * 
         * 
         */
        public List<TripleType> getSubject() {
            if (subject == null) {
                subject = new ArrayList<TripleType>();
            }
            return this.subject;
        }

        /**
         * Gets the value of the abstract property.
         * 
         * @return
         *     possible object is
         *     {@link FreeText }
         *     
         */
        public FreeText getAbstract() {
            return _abstract;
        }

        /**
         * Sets the value of the abstract property.
         * 
         * @param value
         *     allowed object is
         *     {@link FreeText }
         *     
         */
        public void setAbstract(FreeText value) {
            this._abstract = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="productID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="onlineAanvragen"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="ja"/&gt;
     *               &lt;enumeration value="digid"/&gt;
     *               &lt;enumeration value="nee"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="aanvraagURL" type="{http://standaarden.overheid.nl/product/terms/}InformationObject" minOccurs="0"/&gt;
     *         &lt;element name="eenmaligAanmelden" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="ja"/&gt;
     *               &lt;enumeration value="nee"/&gt;
     *               &lt;enumeration value="digi-d"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="contactpunt" type="{http://standaarden.overheid.nl/product/terms/}InformationObject" minOccurs="0"/&gt;
     *         &lt;element name="uniformeProductnaam" type="{http://standaarden.overheid.nl/product/terms/}UniformeProductnaam" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="gerelateerdProduct" type="{http://standaarden.overheid.nl/product/terms/}UniformeProductnaam" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productID",
        "onlineAanvragen",
        "aanvraagURL",
        "eenmaligAanmelden",
        "contactpunt",
        "uniformeProductnaam",
        "gerelateerdProduct"
    })
    public static class Scmeta {

        @XmlElement(required = true)
        protected String productID;
        @XmlElement(required = true)
        protected String onlineAanvragen;
        protected InformationObject aanvraagURL;
        protected String eenmaligAanmelden;
        protected InformationObject contactpunt;
        protected List<UniformeProductnaam> uniformeProductnaam;
        protected List<UniformeProductnaam> gerelateerdProduct;

        /**
         * Gets the value of the productID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductID() {
            return productID;
        }

        /**
         * Sets the value of the productID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductID(String value) {
            this.productID = value;
        }

        /**
         * Gets the value of the onlineAanvragen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnlineAanvragen() {
            return onlineAanvragen;
        }

        /**
         * Sets the value of the onlineAanvragen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnlineAanvragen(String value) {
            this.onlineAanvragen = value;
        }

        /**
         * Gets the value of the aanvraagURL property.
         * 
         * @return
         *     possible object is
         *     {@link InformationObject }
         *     
         */
        public InformationObject getAanvraagURL() {
            return aanvraagURL;
        }

        /**
         * Sets the value of the aanvraagURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link InformationObject }
         *     
         */
        public void setAanvraagURL(InformationObject value) {
            this.aanvraagURL = value;
        }

        /**
         * Gets the value of the eenmaligAanmelden property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEenmaligAanmelden() {
            return eenmaligAanmelden;
        }

        /**
         * Sets the value of the eenmaligAanmelden property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEenmaligAanmelden(String value) {
            this.eenmaligAanmelden = value;
        }

        /**
         * Gets the value of the contactpunt property.
         * 
         * @return
         *     possible object is
         *     {@link InformationObject }
         *     
         */
        public InformationObject getContactpunt() {
            return contactpunt;
        }

        /**
         * Sets the value of the contactpunt property.
         * 
         * @param value
         *     allowed object is
         *     {@link InformationObject }
         *     
         */
        public void setContactpunt(InformationObject value) {
            this.contactpunt = value;
        }

        /**
         * Gets the value of the uniformeProductnaam property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uniformeProductnaam property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUniformeProductnaam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UniformeProductnaam }
         * 
         * 
         */
        public List<UniformeProductnaam> getUniformeProductnaam() {
            if (uniformeProductnaam == null) {
                uniformeProductnaam = new ArrayList<UniformeProductnaam>();
            }
            return this.uniformeProductnaam;
        }

        /**
         * Gets the value of the gerelateerdProduct property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gerelateerdProduct property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGerelateerdProduct().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UniformeProductnaam }
         * 
         * 
         */
        public List<UniformeProductnaam> getGerelateerdProduct() {
            if (gerelateerdProduct == null) {
                gerelateerdProduct = new ArrayList<UniformeProductnaam>();
            }
            return this.gerelateerdProduct;
        }

    }

}
