//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 11:02:21 AM CET 
//


package nl.overheid.standaarden.product.terms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.overheid.standaarden.product.terms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.overheid.standaarden.product.terms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Scproducten }
     * 
     */
    public Scproducten createScproducten() {
        return new Scproducten();
    }

    /**
     * Create an instance of {@link Scproduct }
     * 
     */
    public Scproduct createScproduct() {
        return new Scproduct();
    }

    /**
     * Create an instance of {@link Meta.Owmskern }
     * 
     */
    public Meta.Owmskern createMetaOwmskern() {
        return new Meta.Owmskern();
    }

    /**
     * Create an instance of {@link Meta.Owmsmantel }
     * 
     */
    public Meta.Owmsmantel createMetaOwmsmantel() {
        return new Meta.Owmsmantel();
    }

    /**
     * Create an instance of {@link Meta.Scmeta }
     * 
     */
    public Meta.Scmeta createMetaScmeta() {
        return new Meta.Scmeta();
    }

    /**
     * Create an instance of {@link Body.ProductHTML }
     * 
     */
    public Body.ProductHTML createBodyProductHTML() {
        return new Body.ProductHTML();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link AgentClassOrFreeText }
     * 
     */
    public AgentClassOrFreeText createAgentClassOrFreeText() {
        return new AgentClassOrFreeText();
    }

    /**
     * Create an instance of {@link AgentOrFreeText }
     * 
     */
    public AgentOrFreeText createAgentOrFreeText() {
        return new AgentOrFreeText();
    }

    /**
     * Create an instance of {@link BeslissendOrgaan }
     * 
     */
    public BeslissendOrgaan createBeslissendOrgaan() {
        return new BeslissendOrgaan();
    }

    /**
     * Create an instance of {@link FreeText }
     * 
     */
    public FreeText createFreeText() {
        return new FreeText();
    }

    /**
     * Create an instance of {@link InformationObject }
     * 
     */
    public InformationObject createInformationObject() {
        return new InformationObject();
    }

    /**
     * Create an instance of {@link InformationType }
     * 
     */
    public InformationType createInformationType() {
        return new InformationType();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PeriodOfTime }
     * 
     */
    public PeriodOfTime createPeriodOfTime() {
        return new PeriodOfTime();
    }

    /**
     * Create an instance of {@link TripleType }
     * 
     */
    public TripleType createTripleType() {
        return new TripleType();
    }

    /**
     * Create an instance of {@link UniformeProductnaam }
     * 
     */
    public UniformeProductnaam createUniformeProductnaam() {
        return new UniformeProductnaam();
    }

}
