//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 11:02:21 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://standaarden.overheid.nl/product/terms/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.overheid.standaarden.product.terms;
